### ISSUE TITLE
Roadmap for 0.4.7

### ISSUE THREAD

**Issue by nponeccop** [socketstream/socketstream#619]
I'm going to port an in-house project from 0.4.3 and node 0.10 to 0.4.6 and node 8.x (LTS boron) as the latter seems least broken for the dependencies my project has.

So I volunteer to take over maintenance of the 0.4.x branch from @paulbjensen 

My tasks are essentially:
- [ ] bump and/or fix the deps
- [ ] fix incompatibilities
- [ ] integrate fixes from other branches if any
- [ ] do as many small/easy fixes as humanly possible

**Comment by paulbjensen** [comment]
Hi @nponeccop, please do.

**Comment by nponeccop** [comment]
@paulbjensen The patch is at release candidate stage now. So everybody can test my branch and if it works I can make the commits nicer and we can release **0.4.6** which is basically **a compatibility fix for newer deps and node**. Some `ss-` helpers were branched too, and some security-related changes were pushed to the deps.

It turns out that the changes I made a year ago were enough for my app to work. It just took me long to test them. I test using node 8.17 which is the latest 8.x aka LTS Carbon. It's EOL already unfortunately but it's better/newer than previous versions.

I only motivated to fix what is enough to revive my own app, but if anybody has specific non-compatibility breaking tasks in mind I can take a look. My goal is to support 0.4.x infinitely as long as there are existing users which can give feedback.

**Comment by paulbjensen** [comment]
@nponeccop Hi, sorry I've just stumbled across this message now.

Do you want the branch to be merged into master and then prepare for a 0.4.6 release?

**Comment by nponeccop** [comment]
Yes. Note that you need to merge the helpers as well - I guess ss-hogan and/or ss-stylus

I've been using it for quite a while already.

**Comment by paulbjensen** [comment]
Hi,

That PR was merged into master.

**Comment by nponeccop** [comment]
Great! What's next?

**Comment by nponeccop** [comment]
Ok it's `ss-stylus` and `ss-coffee` pull requests I used:

https://github.com/socketstream/ss-stylus/pull/8
https://github.com/socketstream/ss-coffee/pull/4

They need to be merged, too. Note that I patched an already patched fork in case of ss-stylus

**Comment by paulbjensen** [comment]
Those are merged in. I can give you npm access to the ss-stylus and socketstream npm modules. Do you have a an npm username?

**Comment by nponeccop** [comment]
Yes. It's `nponeccop`. Same as here.

**Comment by paulbjensen** [comment]
Thanks. I've given you access to socketstream and ss-stylus npm packages.
